`timescale 1ns/1ps

// Actual cpu_core + synchronous instruction ROM + the RTL's synchronous RAM.
// Reference files are generated by a Python architectural model, not RTL math.
module mul_pipeline_stress_tb;
    reg clk = 0;
    reg rst_n = 0;
    reg [31:0] inst;
    reg [31:0] rom [0:8191];
    reg [31:0] initial_ram [0:8191];
    reg [31:0] expected_ram [0:8191];
    reg [68:0] reg_trace [0:19999]; // PC, rd, value
    reg [99:0] store_trace [0:19999]; // PC, byte address, byte enables, bus data
    reg [1023:0] rom_file, init_file, ram_file, reg_file, store_file;
    wire [31:0] pc, inst_addr;
    wire prom_ce;
    integer reg_count, store_count, ri, si, failures, cycles, run_no, i, reset_cycle;
    integer tested_words, commits, stores;
    reg finished;

    cpu_core dut(.clk(clk), .rst_n(rst_n), .pc(pc), .inst(inst),
                 .inst_addr(inst_addr), .prom_ce(prom_ce));
    always #5 clk = ~clk;
    always @(posedge clk) begin
        if (!rst_n) inst <= 32'b0;
        else if (prom_ce) inst <= rom[inst_addr[14:2]];
    end

    task check_cycle;
        begin
            if (dut.id_trap_enter === 1'b1)
                $fatal(1, "unexpected trap: cause=%0d pc=%08x", dut.trap_cause, dut.trap_pc);
            if (dut.wb_wr_en === 1'b1 && dut.wb_wr_addr != 0) begin
                if (ri >= reg_count ||
                    {dut.mem_wb_pc, dut.wb_wr_addr, dut.wb_wr_data} !== reg_trace[ri]) begin
                    if (failures < 12) begin
                        $display("FAIL WB[%0d] pc=%08x inst=%08x x%0d=%08x",
                            ri, dut.mem_wb_pc, rom[dut.mem_wb_pc[14:2]],
                            dut.wb_wr_addr, dut.wb_wr_data);
                        if (ri < reg_count)
                            $display("  expected pc=%08x x%0d=%08x", reg_trace[ri][68:37],
                                reg_trace[ri][36:32], reg_trace[ri][31:0]);
                    end
                    failures = failures + 1;
                end
                ri = ri + 1;
            end
            if (dut.mem_ram_s_we !== 4'b0000) begin
                if (si >= store_count ||
                    {dut.ex_mem_pc, dut.ex_mem_alu_result, dut.mem_ram_s_we,
                     dut.mem_ram_w_data} !== store_trace[si]) begin
                    if (failures < 12) begin
                        $display("FAIL STORE[%0d] pc=%08x addr=%08x we=%x data=%08x", si,
                            dut.ex_mem_pc, dut.ex_mem_alu_result, dut.mem_ram_s_we, dut.mem_ram_w_data);
                        if (si < store_count)
                            $display("  expected pc=%08x addr=%08x we=%x data=%08x",
                                store_trace[si][99:68], store_trace[si][67:36],
                                store_trace[si][35:32], store_trace[si][31:0]);
                    end
                    failures = failures + 1;
                end
                si = si + 1;
                if (dut.ex_mem_alu_result == 32'h7ffc &&
                    dut.mem_ram_s_we == 4'b1111 && dut.mem_ram_w_data == 32'h600dcafe)
                    finished = 1;
            end
        end
    endtask

    initial begin
        if (!$value$plusargs("ROM=%s", rom_file) ||
            !$value$plusargs("INIT=%s", init_file) ||
            !$value$plusargs("RAM=%s", ram_file) ||
            !$value$plusargs("REGS=%s", reg_file) ||
            !$value$plusargs("STORES=%s", store_file) ||
            !$value$plusargs("REG_COUNT=%d", reg_count) ||
            !$value$plusargs("STORE_COUNT=%d", store_count)) $fatal(1, "missing image arguments");
        if (reg_count < 1 || reg_count > 20000 || store_count < 1 || store_count > 20000)
            $fatal(1, "invalid reference size");
        $readmemh(rom_file, rom);
        $readmemh(init_file, initial_ram);
        $readmemh(ram_file, expected_ram);
        $readmemh(reg_file, reg_trace, 0, reg_count-1);
        $readmemh(store_file, store_trace, 0, store_count-1);
        failures = 0;
        for (run_no = 0; run_no < 2; run_no = run_no + 1) begin
            @(negedge clk) rst_n = 0;
            repeat (4) @(posedge clk);
            @(negedge clk);
            for (i = 0; i < 8192; i = i + 1) dut.u_ram.ram[i] = initial_ram[i];
            rst_n = 1;
            // Second run first interrupts an active multiply, then starts over.
            if (run_no == 1) begin
                reset_cycle = 0;
                while (!(dut.id_ex_valid && dut.id_ex_is_m_ext) && reset_cycle < 200) begin
                    @(negedge clk);
                    reset_cycle = reset_cycle + 1;
                end
                if (reset_cycle == 200) $fatal(1, "no active multiply for reset test");
                rst_n = 0;
                repeat (4) @(posedge clk);
                @(negedge clk);
                for (i = 0; i < 8192; i = i + 1) dut.u_ram.ram[i] = initial_ram[i];
                rst_n = 1;
            end
            ri = 0;
            si = 0;
            cycles = 0;
            finished = 0;
            while (!finished && cycles < 30000) begin
                @(posedge clk);
                check_cycle();
                cycles = cycles + 1;
            end
            if (!finished) $fatal(1, "TIMEOUT pc=%08x ri=%0d si=%0d", pc, ri, si);
            repeat (8) begin
                @(posedge clk);
                check_cycle();
            end
            #1;
            if (ri != reg_count || si != store_count) begin
                $display("FAIL trace length: registers %0d/%0d stores %0d/%0d", ri, reg_count, si, store_count);
                failures = failures + 1;
            end
            tested_words = 0;
            for (i = 0; i < 8192; i = i + 1) begin
                if (dut.u_ram.ram[i] !== expected_ram[i]) begin
                    if (failures < 12)
                        $display("FAIL RAM[%08x]=%08x expected=%08x", i*4,
                            dut.u_ram.ram[i], expected_ram[i]);
                    failures = failures + 1;
                end
                tested_words = tested_words + 1;
            end
            $display("CHECK run=%0d cycles=%0d WB=%0d stores=%0d RAM words=%0d errors=%0d",
                run_no, cycles, ri, si, tested_words, failures);
        end
        if (failures != 0) $fatal(1, "%0d pipeline/reference mismatches", failures);
        $display("PASS: multiplication pipeline, traces/signatures/flush and active-multiply reset");
        $finish;
    end
endmodule
